<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
    <UserSecretsId>adam-ironlanguage-web-41f99485-63c0-4685-b9e5-93e07b9a36ad</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronLanguage.Db\IronLanguage.Db.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <Content Include="Data\ossetian-russian-dictionary.csv" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
